# Generated by Django 5.2.4 on 2025-07-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habito', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(max_length=200)),
                ('prioridad', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='usuarios.usuarios')),
            ],
        ),
    ]
