# Generated by Django 5.2.4 on 2025-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_habitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitos',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
