# Generated by Django 5.2.4 on 2025-07-17 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_habitos_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habitos',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='habitos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
