# Generated by Django 5.2.4 on 2025-07-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_seguimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('id_notificacion', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
